name: Build Vial Firmware

env:
  KEYBOARD: yangtze
  KEYMAP: 67

on:
  push:
    branches: [main]

jobs:
  build:
    container:
      image: ghcr.io/qmk/qmk_cli:latest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Your Keymap Files
        uses: actions/checkout@v4
        with:
          path: yangtze-qmk

      - name: Checkout Vial-QMK Firmware
        uses: actions/checkout@v4
        with:
          repository: vial-kb/vial-qmk
          path: vial-qmk
          submodules: recursive

      - name: Copy Keymap to Vial-QMK Folder
        run: |
          mv yangtze-qmk vial-qmk/keyboards/$KEYBOARD
          echo "Keymap files copied to vial-qmk/keyboards/$KEYBOARD/keymaps/$KEYMAP/"

      - name: Compile Vial Firmware
        working-directory: ./vial-qmk
        run: |
          make $KEYBOARD:$KEYMAP -j 1
      
      - name: test
        run:
          ls
          echo "----"
          ls vial-qmk/.build

      - name: Upload Firmware Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.KEYBOARD }}_Vial_${{ env.KEYMAP }}_Firmware
          path: |
            vial-qmk/.build/*.hex
            vial-qmk/.build/*.bin
            vial-qmk/.build/*.uf2
          retention-days: 7
